// Regenerate db/seed.sql from src/data/trails.js.
// Run after editing the dataset:  node db/generate-seed.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { trails } from '../src/data/trails.js';

const ORIGIN = {
  slug: 'ortisei',
  name: 'Ortisei',
  region: 'Val Gardena · Dolomites',
  lat: 46.5747,
  lng: 11.6717,
};

const q = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v == null ? 'NULL' : v);

const lines = [
  '-- AUTO-GENERATED by db/generate-seed.mjs — edit src/data/trails.js and re-run.',
  '-- Idempotent: wipes and re-inserts.',
  'DELETE FROM trails;',
  'DELETE FROM origins;',
  '',
  `INSERT INTO origins (id, slug, name, region, lat, lng) VALUES`,
  `  (1, ${q(ORIGIN.slug)}, ${q(ORIGIN.name)}, ${q(ORIGIN.region)}, ${ORIGIN.lat}, ${ORIGIN.lng});`,
  '',
  'INSERT INTO trails (origin_id, slug, name, area, trail_no, difficulty, must_visit, type, season, length_km, ascent_m, duration_h, peak_m, peak_name, massif, access, start_lat, start_lng, peak_lat, peak_lng, path, blurb) VALUES',
];

const rows = trails.map((t) => {
  const vals = [
    1,
    q(t.id),
    q(t.name),
    q(t.area),
    q(t.trail),
    q(t.difficulty),
    t.mustVisit ? 1 : 0,
    q(t.type),
    q(t.season),
    n(t.lengthKm),
    n(t.ascentM),
    n(t.durationH),
    n(t.peakM),
    q(t.peakName),
    q(t.massif),
    q(t.access),
    t.start[0],
    t.start[1],
    t.peak[0],
    t.peak[1],
    q(JSON.stringify(t.path)),
    q(t.blurb),
  ];
  return `  (${vals.join(', ')})`;
});

lines.push(rows.join(',\n') + ';');

const out = join(dirname(fileURLToPath(import.meta.url)), 'seed.sql');
writeFileSync(out, lines.join('\n') + '\n');
console.log(`Wrote ${out} — 1 origin, ${trails.length} trails.`);
