// Regenerate db/seed.sql from src/data/trails.js.
// Run after editing the dataset:  node db/generate-seed.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { origins, trails } from '../src/data/trails.js';

const q = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v == null ? 'NULL' : v);

// origin slug -> 1-based DB id, in declaration order
const originId = new Map(origins.map((o, i) => [o.slug, i + 1]));

const lines = [
  '-- AUTO-GENERATED by db/generate-seed.mjs — edit src/data/trails.js and re-run.',
  '-- Idempotent: wipes and re-inserts.',
  'DELETE FROM trails;',
  'DELETE FROM origins;',
  '',
  `INSERT INTO origins (id, slug, name, region, lat, lng) VALUES`,
  origins
    .map(
      (o, i) =>
        `  (${i + 1}, ${q(o.slug)}, ${q(o.name)}, ${q(o.region)}, ${o.coords[0]}, ${o.coords[1]})`
    )
    .join(',\n') + ';',
  '',
  'INSERT INTO trails (origin_id, slug, name, area, trail_no, difficulty, must_visit, type, season, length_km, ascent_m, duration_h, peak_m, peak_name, massif, access, start_lat, start_lng, peak_lat, peak_lng, path, waypoints, gpx, blurb) VALUES',
];

const rows = trails.map((t) => {
  const oid = originId.get(t.origin);
  if (!oid) throw new Error(`trail '${t.id}' has unknown origin '${t.origin}'`);
  const vals = [
    oid,
    q(t.id),
    q(t.name),
    q(t.area),
    q(t.trail),
    q(t.difficulty),
    t.mustVisit ? 1 : 0,
    q(t.type),
    q(t.season),
    n(t.lengthKm),
    n(t.ascentM),
    n(t.durationH),
    n(t.peakM),
    q(t.peakName),
    q(t.massif),
    q(t.access),
    t.start[0],
    t.start[1],
    t.peak[0],
    t.peak[1],
    q(JSON.stringify(t.path)),
    q(JSON.stringify(t.waypoints ?? [])),
    q(t.gpx),
    q(t.blurb),
  ];
  return `  (${vals.join(', ')})`;
});

lines.push(rows.join(',\n') + ';');

const out = join(dirname(fileURLToPath(import.meta.url)), 'seed.sql');
writeFileSync(out, lines.join('\n') + '\n');
const counts = origins
  .map((o) => `${o.slug}: ${trails.filter((t) => t.origin === o.slug).length}`)
  .join(', ');
console.log(`Wrote ${out} — ${origins.length} origins, ${trails.length} trails (${counts}).`);
